- name: Variables from files
  hosts: local 
  connection: local
  vars_file:
    course.yaml
  tasks:
  - name: Course info from files
    ansible.builtin.debug:
      msg: "Course name is {{ COURSE }}, duration is {{ DURATION }} time, learner is {{ LEARNER }}"